import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    title: "KrishiMarket",
    tagline: "Empowering Farmers, Connecting Markets",
    navHome: "Home",
    navBrowsePrices: "Live Market Prices",
    navBrowseListings: "Crop Listings",
    navFertilizer: "Fertilizer Helper",
    navMessages: "Messages",
    navLogin: "Login",
    navRegister: "Register",
    navLogout: "Logout",
    languageLabel: "English",
    guestWelcome: "Welcome to KrishiMarket",
    guestSub: "Find daily prices of market crops, nearby markets, and crop listings.",
    searchCropsPlaceholder: "Search crops (e.g. Wheat, Rice, Coconut)...",
    searchDistrictsPlaceholder: "Search district/state...",
    browseLivePrices: "Browse Live Market Prices",
    mandiPriceBoard: "Market Price Board",
    nearbyMandis: "Verified Nearby Markets",
    cropListings: "Farmer Crop Listings",
    sellCrop: "Sell Your Crop",
    viewDetails: "View Details",
    contactFarmer: "Contact Farmer",
    fertilizerTool: "Subsidized Fertilizers Helper",
    recommendationTitle: "Fertilizer Recommendations",
    selectCrop: "Select Crop Type",
    selectSoil: "Select Soil Type",
    getRecommendation: "Get Subsidized Recommendations",
    villageLabel: "Village Name",
    districtLabel: "District",
    stateLabel: "State",
    acreageLabel: "Cultivation Acreage (Acres)",
    primaryCropsLabel: "Primary Crops Grown",
    mandiLicenseLabel: "Market License Number",
    registeredMandiName: "Registered Market Name",
    mandiAddress: "Market Address",
    submit: "Submit",
    onboardingTitle: "Complete Your Profile",
    farmerOnboardingSub: "Help us customize your dashboard with crops and location.",
    mandiOnboardingSub: "Verify your identity to post daily prices.",
    dashboardHeader: "Namaste",
    farmerQuestion: "What do you want to do today?",
    btnSellCrop: "Sell Crop (फसल बेचें)",
    btnCheckPrices: "Check Market Prices (बाजार भाव)",
    btnFindFertilizers: "Find Subsidized Fertilizer (उर्वरक सलाह)",
    verified: "Verified",
    pending: "Pending Verification",
    sold: "Sold",
    expectedPrice: "Expected Price",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    volume: "Volume Available",
    qualityGrade: "Quality Grade",
    description: "Description",
    postListingTitle: "Create Crop Listing",
    cropType: "Crop Type",
    expectedPricePerUnit: "Expected Price (₹ per Quintal)",
    quantityQuintal: "Quantity (Quintals)",
    qualityGradeLabel: "Quality Grade",
    optionalDescription: "Optional Description",
    createPostBtn: "Publish Listing",
    todaysArrivals: "Today's Market Arrivals",
    updatePriceBoard: "Update Price Board",
    pendingVerifications: "Pending Farmer Post Verifications",
    mandiAdminDash: "Market Admin Dashboard",
    noListingsFound: "No listings found matching filters.",
    conversations: "Your Chat Inbox",
    senderYou: "You",
    typeMessage: "Type your message here...",
    send: "Send",
    forgotPasswordLink: "Forgot Password?",
    resetPasswordTitle: "Reset Password",
    enterPhoneForOtp: "Enter registered phone number to receive a simulated OTP",
    sendOtpBtn: "Send OTP",
    enterOtpAndNewPassword: "Enter OTP (use 123456) and your new password",
    newPasswordLabel: "New Password",
    resetPasswordBtn: "Reset Password",
    phoneLabel: "Phone Number",
    passwordLabel: "Password",
    nameLabel: "Full Name",
    roleLabel: "User Role",
    roleFarmer: "Farmer (किसान / రైతు)",
    roleMandiOwner: "Market Owner (मार्केट मालिक / యజమాని)",
    roleTrader: "Trader / Buyer / General User",
    backToHome: "Back to Home",
    savedMarkets: "My Saved Markets",
    savedCrops: "My Followed Crops",
    smsAlerts: "Set up SMS Price Alerts"
  },
  hi: {
    title: "कृषि मार्केट",
    tagline: "किसानों को सशक्त बनाना, बाजारों को जोड़ना",
    navHome: "मुख्य पृष्ठ",
    navBrowsePrices: "बाजार भाव (Market Prices)",
    navBrowseListings: "फसल सूची",
    navFertilizer: "खाद सलाह",
    navMessages: "संदेश",
    navLogin: "लॉगिन",
    navRegister: "पंजीकरण",
    navLogout: "लॉगआउट",
    languageLabel: "हिन्दी (Hindi)",
    guestWelcome: "कृषि मार्केट में आपका स्वागत है",
    guestSub: "दैनिक बाजार भाव, आस-पास के बाजार और किसानों की फसल सूचियां देखें।",
    searchCropsPlaceholder: "फसल खोजें (जैसे: गेहूं, नारियल, धान)...",
    searchDistrictsPlaceholder: "जिला/राज्य खोजें...",
    browseLivePrices: "ताजा बाजार भाव देखें",
    mandiPriceBoard: "दैनिक बाजार भाव बोर्ड",
    nearbyMandis: "सत्यापित नजदीकी बाजार",
    cropListings: "बिक्री के लिए उपलब्ध फसलें",
    sellCrop: "फसल बेचें",
    viewDetails: "विवरण देखें",
    contactFarmer: "किसान से संपर्क करें",
    fertilizerTool: "सरकारी सब्सिडी खाद सहायक",
    recommendationTitle: "उर्वरक/खाद सिफारिशें",
    selectCrop: "फसल का प्रकार चुनें",
    selectSoil: "मिट्टी का प्रकार चुनें",
    getRecommendation: "सब्सिडी वाली सिफारिशें प्राप्त करें",
    villageLabel: "गांव का नाम",
    districtLabel: "जिला",
    stateLabel: "राज्य",
    acreageLabel: "खेती का रकबा (एकड़)",
    primaryCropsLabel: "मुख्य फसलें जो आप उगाते हैं",
    mandiLicenseLabel: "मार्केट लाइसेंस संख्या",
    registeredMandiName: "पंजीकृत मार्केट का नाम",
    mandiAddress: "मार्केट का पता",
    submit: "जमा करें",
    onboardingTitle: "अपना प्रोफाइल पूरा करें",
    farmerOnboardingSub: "अपनी स्थान और मुख्य फसलों की जानकारी देकर प्रोफाइल पूरा करें।",
    mandiOnboardingSub: "दैनिक भाव पोस्ट करने के लिए अपनी मार्केट का सत्यापन करें।",
    dashboardHeader: "नमस्ते",
    farmerQuestion: "आज आप क्या करना चाहते हैं?",
    btnSellCrop: "फसल बेचें",
    btnCheckPrices: "बाजार भाव देखें",
    btnFindFertilizers: "सरकारी सब्सिडी खाद सलाह",
    verified: "सत्यापित",
    pending: "सत्यापन लंबित",
    sold: "बिक चुका है",
    expectedPrice: "अपेक्षित मूल्य",
    minPrice: "न्यूनतम भाव",
    maxPrice: "अधिकतम भाव",
    volume: "उपलब्ध मात्रा",
    qualityGrade: "फसल की गुणवत्ता (ग्रेड)",
    description: "विवरण",
    postListingTitle: "बिक्री के लिए नई फसल जोड़ें",
    cropType: "फसल का नाम",
    expectedPricePerUnit: "अपेक्षित भाव (₹ प्रति क्विंटल)",
    quantityQuintal: "मात्रा (क्विंटल)",
    qualityGradeLabel: "गुणवत्ता ग्रेड",
    optionalDescription: "अतिरिक्त विवरण (वैकल्पिक)",
    createPostBtn: "फसल प्रकाशित करें",
    todaysArrivals: "आज की मार्केट आवक",
    updatePriceBoard: "भाव बोर्ड अपडेट करें",
    pendingVerifications: "लंबित फसल सत्यापन अनुरोध",
    mandiAdminDash: "मार्केट व्यवस्थापक डैशबोर्ड",
    noListingsFound: "फिल्टर के अनुसार कोई फसल नहीं मिली।",
    conversations: "संदेश बॉक्स",
    senderYou: "आप",
    typeMessage: "अपना संदेश यहाँ लिखें...",
    send: "भेजें",
    forgotPasswordLink: "पासवर्ड भूल गए?",
    resetPasswordTitle: "पासवर्ड रीसेट",
    enterPhoneForOtp: "सिम्युलेटेड ओटीपी प्राप्त करने के लिए पंजीकृत फोन नंबर दर्ज करें",
    sendOtpBtn: "ओटीपी भेजें",
    enterOtpAndNewPassword: "ओटीपी (123456 दर्ज करें) और नया पासवर्ड दर्ज करें",
    newPasswordLabel: "नया पासवर्ड",
    resetPasswordBtn: "पासवर्ड रीसेट करें",
    phoneLabel: "फ़ोन नंबर",
    passwordLabel: "पासवर्ड",
    nameLabel: "पूरा नाम",
    roleLabel: "आपकी भूमिका",
    roleFarmer: "किसान (Farmer)",
    roleMandiOwner: "मार्केट व्यवस्थापक (Market Owner)",
    roleTrader: "व्यापारी / खरीदार / सामान्य उपयोगकर्ता",
    backToHome: "होम पेज पर जाएं",
    savedMarkets: "मेरी पसंदीदा मार्केट",
    savedCrops: "मेरी पसंदीदा फसलें",
    smsAlerts: "SMS भाव अलर्ट सेट करें"
  },
  te: {
    title: "కృషి మార్కెట్",
    tagline: "రైతులకు సాధికారత, మార్కెట్లను అనుసంధానించడం",
    navHome: "హోమ్",
    navBrowsePrices: "లైవ్ మార్కెట్ ధరలు",
    navBrowseListings: "పంటల జాబితా",
    navFertilizer: "ఎరువుల సహాయకం",
    navMessages: "సందేశాలు",
    navLogin: "లాగిన్",
    navRegister: "రిజిస్టర్",
    navLogout: "లాగౌట్",
    languageLabel: "తెలుగు (Telugu)",
    guestWelcome: "కృషి మార్కెట్‌కు స్వాగతం",
    guestSub: "దైనందిన మార్కెట్ ధరలు, సమీప మార్కెట్లు మరియు పంటల జాబితాలను కనుగొనండి.",
    searchCropsPlaceholder: "పంటలను వెతకండి (ఉదా: వరి, కొబ్బరికాయ, మొక్కజొన్న)...",
    searchDistrictsPlaceholder: "జిల్లా/రాష్ట్రం వెతకండి...",
    browseLivePrices: "తాజా మార్కెట్ ధరలు చూడండి",
    mandiPriceBoard: "మార్కెట్ ధరల పట్టిక",
    nearbyMandis: "ధృవీకరించబడిన సమీప మార్కెట్లు",
    cropListings: "రైతుల పంటల జాబితాలు",
    sellCrop: "మీ పంటను అమ్మండి",
    viewDetails: "వివరాలు చూడండి",
    contactFarmer: "రైతును సంప్రదించండి",
    fertilizerTool: "సబ్సిడీ ఎరువుల సహాయకం",
    recommendationTitle: "ఎరువుల సిఫార్సులు",
    selectCrop: "పంట రకాన్ని ఎంచుకోండి",
    selectSoil: "నేల రకాన్ని ఎంచుకోండి",
    getRecommendation: "సబ్సిడీ సిఫార్సులను పొందండి",
    villageLabel: "గ్రామము పేరు",
    districtLabel: "జిల్లా",
    stateLabel: "రాష్ట్రం",
    acreageLabel: "సాగు భూమి వైశాల్యం (ఎకరాలు)",
    primaryCropsLabel: "పండించే ప్రధాన పంటలు",
    mandiLicenseLabel: "మార్కెట్ లైసెన్స్ నంబర్",
    registeredMandiName: "నమోదిత మార్కెట్ పేరు",
    mandiAddress: "మార్కెట్ చిరునామా",
    submit: "సమర్పించు",
    onboardingTitle: "మీ ప్రొఫైల్‌ను పూర్తి చేయండి",
    farmerOnboardingSub: "పంటలు మరియు స్థానంతో మీ ప్రొఫైల్‌ను పూర్తి చేయడానికి మాకు సహాయపడండి.",
    mandiOnboardingSub: "ధరలను పోస్ట్ చేయడానికి మీ మార్కెట్‌ను ధృవీకరించండి.",
    dashboardHeader: "నమస్తే",
    farmerQuestion: "ఈరోజు మీరు ఏమి చేయాలనుకుంటున్నారు?",
    btnSellCrop: "పంట అమ్మండి",
    btnCheckPrices: "మార్కెట్ ధరలు చూడండి",
    btnFindFertilizers: "సబ్సిడీ ఎరువుల సలహా",
    verified: "ధృవీకరించబడింది",
    pending: "ధృవీకరణ పెండింగ్‌లో ఉంది",
    sold: "అమ్ముడైపోయింది",
    expectedPrice: "ఆశించిన ధర",
    minPrice: "కనీస ధర",
    maxPrice: "గరిష్ట ధర",
    volume: "అందుబాటులో ఉన్న పరిమాణం",
    qualityGrade: "నాణ్యత గ్రేడ్",
    description: "వివరణ",
    postListingTitle: "కొత్త పంట జాబితాను సృష్టించండి",
    cropType: "పంట రకం",
    expectedPricePerUnit: "ఆశించిన ధర (₹ క్వింటాల్‌కు)",
    quantityQuintal: "పరిమాణం (క్వింటాళ్ళు)",
    qualityGradeLabel: "నాణ్యత గ్రేడ్",
    optionalDescription: "ఐచ్ఛిక వివరణ",
    createPostBtn: "పంటను ప్రచురించు",
    todaysArrivals: "ఈరోజు మార్కెట్ రాకలు",
    updatePriceBoard: "ధరల పట్టికను నవీకరించండి",
    pendingVerifications: "పెండింగ్ రైతు పోస్ట్ ధృవీకరణలు",
    mandiAdminDash: "మార్కెట్ అడ్మిన్ డాష్‌బోర్డ్",
    noListingsFound: "పంట వివరాలు ఏవీ లభించలేదు.",
    conversations: "మీ చాట్ ఇన్‌బాక్స్",
    senderYou: "మీరు",
    typeMessage: "మీ సందేశాన్ని ఇక్కడ టైప్ చేయండి...",
    send: "పంపండి",
    forgotPasswordLink: "పాస్‌వర్డ్ మరిచిపోయారా?",
    resetPasswordTitle: "పాస్‌వర్డ్ రీసెట్",
    enterPhoneForOtp: "ఓటిపి కోసం మీ ఫోన్ నంబర్ నమోదు చేయండి",
    sendOtpBtn: "ఓటిపి పంపు",
    enterOtpAndNewPassword: "ఓటిపి (123456) మరియు కొత్త పాస్‌వర్డ్ నమోదు చేయండి",
    newPasswordLabel: "కొత్త పాస్‌వర్డ్",
    resetPasswordBtn: "పాస్‌వర్డ్ రీసెట్ చేయి",
    phoneLabel: "ఫోన్ నంబర్",
    passwordLabel: "పాస్‌వర్డ్",
    nameLabel: "పూర్తి పేరు",
    roleLabel: "వినియోగదారు పాత్ర",
    roleFarmer: "రైతు (Farmer)",
    roleMandiOwner: "మార్కెట్ అడ్మిన్ (Market Owner)",
    roleTrader: "వ్యాపారి / కొనుగోలుదారు / సాధారణ వినియోగదారు",
    backToHome: "హోమ్ పేజీకి వెళ్ళు",
    savedMarkets: "నా సేవ్ చేసిన మార్కెట్లు",
    savedCrops: "నా అనుసరించే పంటలు",
    smsAlerts: "SMS ధర అలర్ట్ సెట్ చేయి"
  },
  mr: {
    title: "कृषि मार्केट",
    tagline: "शेतकऱ्यांना सक्षम करणे, बाजारांना जोडणे",
    navHome: "होम",
    navBrowsePrices: "थेट बाजार भाव",
    navBrowseListings: "पीक यादी",
    navFertilizer: "खत सल्लागार",
    navMessages: "संदेश",
    navLogin: "लॉगिन",
    navRegister: "नोंदणी",
    navLogout: "लॉगआउट",
    languageLabel: "मराठी (Marathi)",
    guestWelcome: "कृषि मार्केटमध्ये आपले स्वागत आहे",
    guestSub: "दैनिक बाजार भाव, जवळील बाजारपेठा आणि शेतकऱ्यांच्या पीक याद्या पहा.",
    searchCropsPlaceholder: "पीक शोधा (उदा: गहू, तांदूळ, नारळ, मका)...",
    searchDistrictsPlaceholder: "जिल्हा/राज्य शोधा...",
    browseLivePrices: "थेट बाजार भाव पहा",
    mandiPriceBoard: "बाजार भाव फलक",
    nearbyMandis: "सत्यापित जवळील बाजार",
    cropListings: "विक्रीसाठी उपलब्ध पिके",
    sellCrop: "आपले पीक विका",
    viewDetails: "तपशील पहा",
    contactFarmer: "शेतकऱ्याशी संपर्क साधा",
    fertilizerTool: "सरकारी खत सहाय्यक",
    recommendationTitle: "खत शिफारसी",
    selectCrop: "पीक निवडा",
    selectSoil: "मातीचा प्रकार निवडा",
    getRecommendation: "खत शिफारसी मिळवा",
    villageLabel: "गावाचे नाव",
    districtLabel: "जिल्हा",
    stateLabel: "राज्य",
    acreageLabel: "सागु क्षेत्र (एकर)",
    primaryCropsLabel: "घेतली जाणारी मुख्य पिके",
    mandiLicenseLabel: "मार्केट परवाना क्रमांक",
    registeredMandiName: "नोंदणीकृत मार्केटचे नाव",
    mandiAddress: "मार्केटचा पत्ता",
    submit: "सबमिट करा",
    onboardingTitle: "आपली प्रोफाईल पूर्ण करा",
    farmerOnboardingSub: "आपली पिके आणि स्थानाची माहिती देऊन नोंदणी पूर्ण करा.",
    mandiOnboardingSub: "दैनिक भाव अपडेट करण्यासाठी आपल्या मार्केटचे सत्यापन करा.",
    dashboardHeader: "नमस्ते",
    farmerQuestion: "आज आपण काय करू इच्छिता?",
    btnSellCrop: "पीक विका",
    btnCheckPrices: "बाजार भाव पहा",
    btnFindFertilizers: "सरकारी खत सल्ला",
    verified: "सत्यापित",
    pending: "सत्यापन प्रलंबित",
    sold: "विकले गेले",
    expectedPrice: "अपेक्षित किंमत",
    minPrice: "न्यूनतम भाव",
    maxPrice: "कमाल भाव",
    volume: "उपलब्ध प्रमाण",
    qualityGrade: "गुणवत्ता श्रेणी (ग्रेड)",
    description: "वर्णन",
    postListingTitle: "विक्रीसाठी नवीन पीक जोडा",
    cropType: "पिकाचा प्रकार",
    expectedPricePerUnit: "अपेक्षित भाव (₹ प्रति क्विंटल)",
    quantityQuintal: "प्रमाण (क्विंटल)",
    qualityGradeLabel: "गुणवत्ता श्रेणी",
    optionalDescription: "अतिरिक्त वर्णन (वैकल्पिक)",
    createPostBtn: "पीक प्रकाशित करा",
    todaysArrivals: "आजची बाजार आवक",
    updatePriceBoard: "भाव फलक अपडेट करा",
    pendingVerifications: "प्रलंबित पीक सत्यापन विनंती",
    mandiAdminDash: "मार्केट व्यवस्थापक डॅशबोर्ड",
    noListingsFound: "फिल्टरनुसार पीक आढळले नाही.",
    conversations: "संदेश बॉक्स",
    senderYou: "तुम्ही",
    typeMessage: "आपला संदेश येथे लिहा...",
    send: "पाठवा",
    forgotPasswordLink: "पासवर्ड विसरलात?",
    resetPasswordTitle: "पासवर्ड रीसेट",
    enterPhoneForOtp: "सिम्युलेटेड ओटीपी प्राप्त करण्यासाठी नोंदणीकृत फोन नंबर प्रविष्ट करा",
    sendOtpBtn: "ओटीपी पाठवा",
    enterOtpAndNewPassword: "ओटीपी (123456 प्रविष्ट करा) आणि नवीन पासवर्ड टाका",
    newPasswordLabel: "नवीन पासवर्ड",
    resetPasswordBtn: "पासवर्ड रीसेट करा",
    phoneLabel: "फोन नंबर",
    passwordLabel: "पासवर्ड",
    nameLabel: "पूर्ण नाव",
    roleLabel: "वापरकर्त्याची भूमिका",
    roleFarmer: "शेतकरी (Farmer)",
    roleMandiOwner: "मार्केट मालक (Market Owner)",
    roleTrader: "व्यापारी / खरेदीदार / सामान्य वापरकर्ता",
    backToHome: "होम पेजवर जा",
    savedMarkets: "माझे आवडते मार्केट",
    savedCrops: "माझी आवडती पिके",
    smsAlerts: "SMS भाव अलर्ट सेट करा"
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState(() => {
    return localStorage.getItem('krishi_locale') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('krishi_locale', locale);
  }, [locale]);

  const toggleLanguage = () => {
    // Falls back to cycling or we can set locale directly
    const cycle = { en: 'hi', hi: 'te', te: 'mr', mr: 'en' };
    setLocale((prev) => cycle[prev] || 'en');
  };

  const setLanguage = (lang) => {
    if (['en', 'hi', 'te', 'mr'].includes(lang)) {
      setLocale(lang);
    }
  };

  const t = (key) => {
    const dict = translations[locale] || translations['en'];
    return dict[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale: setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
